import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased gap-4 flex flex-col min-h-screen bg-gray-100 text-gray-900 dark:bg-gray-700 dark:text-gray-100 m-8`}
      >
        <h1>I am the Root layout, I wrap everything, I am always here</h1>
        {children}
      </body>
    </html>
  )
}
